#!/usr/bin/python3
#SPDX-FileCopyrightText: 2023 Nozaki
#SPDX-License-Identifier: BSD-3-Clause 

from datetime import datetime

def what_time():
    now = datetime.now()
    return now.strftime("%Y年%m月%d日 %H時%M分%S秒")

if __name__ == "__main__":
    print(what_time())
